* Chapter 1

** DONE Fix problem importing 'level'
  CLOSED: [2019-02-04 Mon 13:19]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2019-02-04 Mon 13:19]
  :END:

I had the following when attempting to import 'level' in bool.agda:

.../verified_fp_agda/01/bool.agda:3,13-18
The file /usr/local/Cellar/agda/2.5.4.2/lib/agda/src/Level.agda can be accessed via several project roots. Both Level and level point to this file.
When scope checking the declaration open import level


My temporary fix for this is to create 'level' locally and rename to 'level_'. Then, open import 'level_'

I solved it by doing the following:
1. clone https://github.com/williamdemeo/ial
2. Per it README.md:
     + cd to ~/.agda, and add a file called "libraries" to it (if it doesn't already exist), containing the full path to the .agda-lib file contained in this directory (for the IAL version 1.3).
     + Then create a file called "defaults", and add the word "IAL" to it (no quotes). 
     + These steps tell Agda where the IAL library is, and that you want to include it when opening .agda files in emacs (or with the command-line tool).

This allowed me to work in ial/1.3 without any name clashes. But to work in this [[https://github.com/adkelley/verified_fp_agda][repository]], I needed to copy bool.agda and level.agda from ial/1.3 into chapter [[https://github.com/adkelley/verified_fp_agda/tree/master/01][01]] and rename 
them to bool1.agda and level1.agda.

** Exercises
   1.1
     (a) tt
     (b) ff
     (c) ff
   1.2
     (a) 𝔹
     (b) 𝔹
     (c) 𝔹 → 𝔹 → 𝔹
     (d) Set
   1.3
     [[file:./01/my-bool.agda][my-bool.agda]]
   1.4
   [[file:./01/days.agda][  days.agda]]
   1.5
   [[file:./01/days.agda][  days.agda]]
   1.6
   [[file:./01/suits.agda][  suits]]
   1.7
   [[file:./01/suits.agda][  suits]]
